# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = SnailAnalyst
DESTDIR = ./Win32/Release
CONFIG += debug
DEFINES += _UNICODE WIN64 NOMINMAX
LIBS += -lzlib \
    -lpython27
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += GeneratedFiles
RCC_DIR += .
include(SnailAnalyst.pri)
